name: Delete old runs for specific work flow
on: [ push ]    

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: mwigginsdev/delete-oldest-workflow-runs@main
        with:
          token: ${{ secrets.pat }}
          repository: ${{ github.repository }}
          keep_minimum_runs: '10'
          workflow_name: 'Setup and run Terraform'