name: Delete old workflow runs
on: [push]

name: Delete old runs for specific work flow
on:
  workflow_dispatch:
    inputs:
      minimumRunsToKeep:
        description: 'Number of workflow runs to keep'
        required: true
        default: 10
      workflowName:
        description: 'Name of workflow to delete from'
        required: true
        default: 'Setup and run Terraform'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: mwigginsdev/delete-oldest-workflow-runs@main
        with:
          token: ${{ secrets.pat }}
          repository: ${{ github.repository }}
          keep_minimum_runs: ${{ github.event.inputs.minimumRunsToKeep }}
          workflow_name: ${{ github.event.inputs.workflowName }}