name: Setup and run Terraform
on: [push]
jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - id: terraform_plan
        uses: sturlabragason/terraform_state_artifact@v1
        with:
          encryptionkey: ${{ secrets.pat }}
          apply: false