name: Setup and run Terraform
on: [push]
jobs:
  terraform_refresh_only_job:
    runs-on: ubuntu-latest
    steps:
    - uses: sturlabragason/terraform_state_artifact@v1
      with:
        encryptionkey: ${{ secrets.pat }}
        custom_apply_flags: '-refresh-only'
      env: 
        TF_VAR_pat: ${{ secrets.pat }}
  terraform_job:
    runs-on: ubuntu-latest
    needs: terraform_refresh_only_job
    steps:
    - uses: sturlabragason/terraform_state_artifact@v1
      with:
        encryptionkey: ${{ secrets.pat }}
      env: 
        TF_VAR_pat: ${{ secrets.pat }}