name: Setup and run Terraform
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '11 11 11 * *'
jobs:
  terraform_refresh_only_job:
    runs-on: ubuntu-latest
    steps:
    - uses: sturlabragason/terraform_state_artifact@v1
      with:
        encryptionkey: ${{ secrets.pat }}
        custom_apply_flags: '-refresh-only'
      env: 
        TF_VAR_pat: ${{ secrets.pat }}
  terraform_job:
    runs-on: ubuntu-latest
    needs: terraform_refresh_only_job
    steps:
    - uses: sturlabragason/terraform_state_artifact@v1
      with:
        encryptionkey: ${{ secrets.pat }}
      env: 
        TF_VAR_pat: ${{ secrets.pat }}
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        output-file: readme.md
        output-method: inject
        git-push: "true"
